version: '3.9'

services:
  edusphere:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=ELearning;User Id=sa;Password=!Passw0rd;Encrypt=True;TrustServerCertificate=True;
    networks:
      - edusphere-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/favicon.ico"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - edusphere-net
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "!Passw0rd", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  edusphere-net:

volumes:
  sql-data:
